# Generated by Django 4.2.13 on 2026-02-22 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Steel', 'Steel'), ('Cement', 'Cement'), ('Timber', 'Timber'), ('Safety', 'Safety'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Tools', 'Tools'), ('Other', 'Other')], default='Other', max_length=30)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_stock_threshold', models.FloatField(default=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
